# Generated by Django 4.2 on 2023-04-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_element_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
